-
  name: 'Deploy a WebApplication'
  hosts: Target1
  tasks:
    - name: Ping Testing
      ping:

    - name: Installing Dependency
      become: true
      become_method: sudo
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
