-
  name: 'Deploy a WebApplication'
  hosts: Target1
  tasks:
    - name: Ping Testing
      ping:

    - name: Installing MySQL Database
      become: true
      become_method: sudo
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql-client
